export const GET_ALL_COUNTRY_DATA_SUCCESS = 'GET_ALL_COUNTRY_DATA_SUCCESS';
export const DATA_BY_REGION = 'DATA_BY_REGION';
export const SINGLE_COUNTRY_DATA_SUCCESS = 'SINGLE_COUNTRY_DATA_SUCCESS';
export const SEARCH_COUNTRY_SUCCESS = 'SEARCH_COUNTRY_SUCCESS';
export const COLOR_CHANGE_SUCCESS = 'COLOR_CHANGE_SUCCESS';

